name: 'Verify git ref'
description: 'Verify GPG signed commits or tags'

inputs:

  public_key_dir:
    description: "Path to directory with public keys to import"
    required: true

  ref:
    description: "Git reference (HEAD, master, tag, ...)"
    default: HEAD

  num_required:
    description: "Number of required signatures"
    default: 1

  git_options:
    description: "Options passed to git"

runs:
  using: docker
  image: docker://atmoz/git-verify-ref
  args:
    - ${{ inputs.public_key_dir }}
    - ${{ inputs.ref }}
    - ${{ inputs.num_required }}
    - ${{ inputs.git_options }}
