name: build

on:
  push:
  pull_request:

env:
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Run ShellCheck
        uses: ludeeus/action-shellcheck@master

      - name: Build image
        run: |
          docker build . \
            --pull=true \
            --file=Dockerfile \
            --tag="$IMAGE_NAME" \
            --tag="$IMAGE_NAME:$GITHUB_SHA" \
            --label="org.opencontainers.image.source=$GITHUB_SERVER_URL/$GITHUB_REPOSITORY" \
            --label="org.opencontainers.image.revision=$GITHUB_SHA" \
            --label="org.opencontainers.image.created=$(date --rfc-3339=seconds)"

      - name: Test action
        uses: ./
        with:
          public_key_dir: public-keys

      - name: Push images to Docker Hub registry
        if: github.event_name != 'pull_request' && github.ref == 'refs/heads/master'
        run: |
          docker login \
            -u "${{ secrets.DOCKER_HUB_USERNAME }}" \
            -p "${{ secrets.DOCKER_HUB_PASSWORD }}"

          docker push $IMAGE_NAME # no tags specified to include all tags

          #- name: Push image to GitHub registry
          #  if: github.event_name != 'pull_request' && github.ref == 'refs/heads/master'
          #  run: |
          #    docker login docker.pkg.github.com \
          #      -u "${{ github.actor }}" \
          #      -p "${{ secrets.GITHUB_TOKEN }}"

          #    TAG=docker.pkg.github.com/$GITHUB_REPOSITORY/$IMAGE_NAME
          #    docker tag $IMAGE_NAME $TAG
          #    docker push $TAG


